### ISSUE TITLE
Build issues, nim reports a type mismatch

### ISSUE THREAD

**Issue by jonaudet** [andreas-wilm/lofreq3#13]
Hi, I am trying to install LoFreq3 on Ubuntu 18.04 (on the Windows Subsystem for Linux). Nim installed properly but is reporting the errors below when building LoFreq3. (this is the end of a long list of "hints", but seems like the most useful part...)

 ... /home/user/lofreq3/src/lofreqpkg/pileup/storage/slidingDeque.nim(111, 6) Hint: '[]' is declared but not used [XDeclaredButNotUsed]
        ... Hint: recordFilter [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: iSequence [Processing]
        ... Hint: processor [Processing]
        ... /home/user/lofreq3/src/lofreqpkg/pileup/algorithm.nim(140, 16) Error: type mismatch: got <Processor[slidingDeque.SlidingDeque], int64>
        ... but expected one of:
        ... proc beginRead(self: Processor; start: int): void
        ...   first type mismatch at position: 2
        ...   required type for start: int
        ...   but expression 'start(read)' is of type: int64
        ... expression: beginRead(processor, start(read))

**Comment by andreas-wilm** [comment]
Sorry, I fixed this on the viterbi branch, which I haven't merged into master yet. You can see it's not prime time yet for this version...I'll get this stable as soon as I can. In the meantime, please give the viterbi branch a go

**Comment by jonaudet** [comment]
That worked, thanks.
