### ISSUE TITLE
gatk indel qualities

### ISSUE THREAD

**Issue by jeongmeani** [andreas-wilm/lofreq3#16]
Hi, 

using lofreq, i analysis WES data to discover variant.

but the indel output vcf does not any indel.
so i check manual again, i realize indel qualities is required for indel calling.

but my bam file is carried out to BQSR. 
and i could not search any information about indel qualities of BQSR.

so i want to check 'indel qualities'
how can i?

Best Regards

Jeongmin

**Comment by andreas-wilm** [comment]
Hi Jeongmin, I think GATK recently stopped adding indel qualities (BI and BD tags) to the BAM during BQSR. You can add those with `lofreq indel` (best with `--dindel`).
