### ISSUE TITLE
Error: unhandled exception: index 89678 not in 0 .. 89677 [IndexDefect] 

### ISSUE THREAD

**Issue by EmilianaWeiss** [andreas-wilm/lofreq3#41]
I am try to run a package lofreq3 for nanopore data (UL) and for some reason viterbi s not working properly.

Error:

./lofreq viterbi -f=/home/guest1/Desktop/HSA_chr/KY962518_tandem_union.fasta -b='/home/guest1/Desktop/UL_guppy4/HG002_ultra_tandem_filterK.bam' > '/home/guest1/Desktop/UL_guppy4/HG002_ultra_tandem_filterK_viterbi.bam'
/home/guest1/.nimble/pkgs/cligen-1.4.1/cligen.nim(1024) lofreq
/home/guest1/.nimble/pkgs/cligen-1.4.1/cligen.nim(676) multiSubs
/home/guest1/.nimble/pkgs/cligen-1.4.1/cligen.nim(758) multi
/home/guest1/.nimble/pkgs/cligen-1.4.1/cligen.nim(676) dispatchviterbi
/home/guest1/lofreq3/src/lofreqpkg/viterbi.nim(217) viterbi
/home/guest1/lofreq3/src/lofreqpkg/viterbi.nim(59) getRefContext
/home/guest1/nim-1.4.2/lib/system.nim(2496) []
/home/guest1/nim-1.4.2/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: index 89678 not in 0 .. 89677 [IndexDefect]

I am using nim-1.4.2.

I have clean the cache, and it still does not work.

There is anything else that you suggest?

**Comment by andreas-wilm** [comment]
Thanks for giving this a try! I've fixed this already on the devel branch. See also https://github.com/andreas-wilm/lofreq3/issues/30. Can I send you a statically compiled binary? If yes, please share your address with me: <andreas.wilm@gmail.com>. Alternatively, please wait for a week and RC2 will be released (including a binary).
